[workspace]
members = [
	"crates/hl-code",
	"crates/hl-code-derive",
	"crates/hl-ffi",
	"crates/hl-sys",
]

[package]
name = "hl-jit"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 WITH LLVM-exception"

[features]
default = ["hl-ffi"]
libffi = []

[dependencies]
backtrace = "0.3.74"
clap = { version = "4.5.31", features = ["derive"] }
cranelift = { git = "https://github.com/tobil4sk/wasmtime", branch = "feature/cranelift-aarch64-fcmp", features = [
	"jit",
	"module",
	"native",
	"object",
] }
cranelift-codegen = { git = "https://github.com/tobil4sk/wasmtime", branch = "feature/cranelift-aarch64-fcmp", features = ["all-native-arch"] }
libloading = "0.8.6"
hl-code = { path = "crates/hl-code" }
hl-sys = { path = "crates/hl-sys" }
hl-ffi = { path = "crates/hl-ffi", optional = true }
libc = "0.2.171"
tempfile = "3.19.0"
target-lexicon = "0.13.2"
ar_archive_writer = "0.4.2"
clap_complete = { version = "4.5.48", features = ["unstable-dynamic"] }
rayon = "1.10.0"

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.60.2", features = ["Win32_System_LibraryLoader"] }

[build-dependencies]
cc = "1.2.16"
